#!/bin/sh

# install required tools
sudo apt --assume-yes update
sudo apt --assume-yes install build-essential procps curl file git

# install homebrew
bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# add homebrew to path
cat <<'EOF' >> "$HOME/.bashrc" 
if [ -e /home/linuxbrew/.linuxbrew ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
EOF
