#!/bin/sh

# Missing packages:
# bash-language-server (will be installed using npm)
# lua-language-server
# rust-analyzer (will be installed using rustup)
install_packages() {
    sudo apt -y update
    sudo apt -y install \
        build-essential \
        clangd \
        cmake \
        default-jre \
        fd-find \
        neovim \
        npm \
        ripgrep \
        rustup \
        shellcheck \
        tree-sitter-cli \
        yt-dlp
}

install_bashlsp() {
    INSTALL_DIR="/tmp/bash-language-server"
    npm --prefix "$INSTALL_DIR" install --global bash-language-server
    sudo chown --recursive root:root "$INSTALL_DIR"
    sudo mv "$INSTALL_DIR/bin/bash-language-server" "/usr/local/bin"
    sudo mv "$INSTALL_DIR/lib/node_modules" "/usr/local/lib"
    sudo rm --force --recursive "$INSTALL_DIR"
    unset INSTALL_DIR
}

install_rusttools() {
    rustup default stable
    rustup component add clippy
    rustup component add rustfmt
    rustup component add rust-analyzer
}

fix_clang_formatting() {
    cat > "$HOME/.clang-format" <<EOF
---
BasedOnStyle: LLVM
IndentWidth: 4
EOF
}

install_packages
install_bashlsp
install_rusttools
fix_clang_formatting
